#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: c1050fe
#
Name     : qt6scxml
Version  : 6.6.1
Release  : 5
URL      : https://download.qt.io/official_releases/qt/6.6/6.6.1/submodules/qtscxml-everywhere-src-6.6.1.tar.xz
Source0  : https://download.qt.io/official_releases/qt/6.6/6.6.1/submodules/qtscxml-everywhere-src-6.6.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-3.0
Requires: qt6scxml-lib = %{version}-%{release}
Requires: qt6scxml-libexec = %{version}-%{release}
Requires: qt6scxml-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : mesa-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the qt6scxml package.
Group: Development
Requires: qt6scxml-lib = %{version}-%{release}
Provides: qt6scxml-devel = %{version}-%{release}
Requires: qt6scxml = %{version}-%{release}

%description dev
dev components for the qt6scxml package.


%package lib
Summary: lib components for the qt6scxml package.
Group: Libraries
Requires: qt6scxml-libexec = %{version}-%{release}
Requires: qt6scxml-license = %{version}-%{release}

%description lib
lib components for the qt6scxml package.


%package libexec
Summary: libexec components for the qt6scxml package.
Group: Default
Requires: qt6scxml-license = %{version}-%{release}

%description libexec
libexec components for the qt6scxml package.


%package license
Summary: license components for the qt6scxml package.
Group: Default

%description license
license components for the qt6scxml package.


%prep
%setup -q -n qtscxml-everywhere-src-6.6.1
cd %{_builddir}/qtscxml-everywhere-src-6.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1703026291
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1703026291
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt6scxml
cp %{_builddir}/qtscxml-everywhere-src-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/qt6scxml/b073f11f0c81a95ab5e32aa6b5d23a5955a95274 || :
cp %{_builddir}/qtscxml-everywhere-src-%{version}/LICENSES/GFDL-1.3-no-invariants-only.txt %{buildroot}/usr/share/package-licenses/qt6scxml/715f995f11805ee85601834220c43b082f457ea3 || :
cp %{_builddir}/qtscxml-everywhere-src-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qt6scxml/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qtscxml-everywhere-src-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6scxml/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qtscxml-everywhere-src-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6scxml/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/qtscxml-everywhere-src-%{version}/tests/3rdparty/scion-tests/LICENSE.txt %{buildroot}/usr/share/package-licenses/qt6scxml/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/qtscxml-everywhere-src-%{version}/tests/3rdparty/scion-tests/scxml-test-framework/LICENSE.txt %{buildroot}/usr/share/package-licenses/qt6scxml/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/qt6/metatypes/qt6scxml_relwithdebinfo_metatypes.json
/usr/lib64/qt6/metatypes/qt6statemachine_relwithdebinfo_metatypes.json
/usr/lib64/qt6/mkspecs/features/qscxmlc.prf
/usr/lib64/qt6/mkspecs/modules/qt_lib_scxml.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_scxml_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_statemachine.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_statemachine_private.pri
/usr/lib64/qt6/modules/Scxml.json
/usr/lib64/qt6/modules/StateMachine.json

%files dev
%defattr(-,root,root,-)
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmlcompiler_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmlcppdatamodel_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmldatamodel_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmldatamodelplugin_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmlevent_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmlexecutablecontent_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmlglobals_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmlinvokableservice_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmlstatemachine_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmlstatemachineinfo_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qscxmltabledata_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qtscxml-config_p.h
/usr/include/QtScxml/6.6.1/QtScxml/private/qtscxmlexports_p.h
/usr/include/QtScxml/QScxmlCompiler
/usr/include/QtScxml/QScxmlCppDataModel
/usr/include/QtScxml/QScxmlDataModel
/usr/include/QtScxml/QScxmlDynamicScxmlServiceFactory
/usr/include/QtScxml/QScxmlError
/usr/include/QtScxml/QScxmlEvent
/usr/include/QtScxml/QScxmlInvokableService
/usr/include/QtScxml/QScxmlInvokableServiceFactory
/usr/include/QtScxml/QScxmlNullDataModel
/usr/include/QtScxml/QScxmlStateMachine
/usr/include/QtScxml/QScxmlStaticScxmlServiceFactory
/usr/include/QtScxml/QScxmlTableData
/usr/include/QtScxml/QtScxml
/usr/include/QtScxml/QtScxmlDepends
/usr/include/QtScxml/QtScxmlVersion
/usr/include/QtScxml/qscxmlcompiler.h
/usr/include/QtScxml/qscxmlcppdatamodel.h
/usr/include/QtScxml/qscxmldatamodel.h
/usr/include/QtScxml/qscxmlerror.h
/usr/include/QtScxml/qscxmlevent.h
/usr/include/QtScxml/qscxmlexecutablecontent.h
/usr/include/QtScxml/qscxmlglobals.h
/usr/include/QtScxml/qscxmlinvokableservice.h
/usr/include/QtScxml/qscxmlnulldatamodel.h
/usr/include/QtScxml/qscxmlstatemachine.h
/usr/include/QtScxml/qscxmltabledata.h
/usr/include/QtScxml/qtscxml-config.h
/usr/include/QtScxml/qtscxmlexports.h
/usr/include/QtScxml/qtscxmlversion.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qabstractstate_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qabstracttransition_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qbasickeyeventtransition_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qbasicmouseeventtransition_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qeventtransition_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qfinalstate_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qhistorystate_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qsignaleventgenerator_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qsignaltransition_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qstate_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qstatemachine_p.h
/usr/include/QtStateMachine/6.6.1/QtStateMachine/private/qtstatemachine-config_p.h
/usr/include/QtStateMachine/QAbstractState
/usr/include/QtStateMachine/QAbstractTransition
/usr/include/QtStateMachine/QEventTransition
/usr/include/QtStateMachine/QFinalState
/usr/include/QtStateMachine/QHistoryState
/usr/include/QtStateMachine/QKeyEventTransition
/usr/include/QtStateMachine/QMouseEventTransition
/usr/include/QtStateMachine/QSignalTransition
/usr/include/QtStateMachine/QState
/usr/include/QtStateMachine/QStateMachine
/usr/include/QtStateMachine/QtStateMachine
/usr/include/QtStateMachine/QtStateMachineDepends
/usr/include/QtStateMachine/QtStateMachineVersion
/usr/include/QtStateMachine/qabstractstate.h
/usr/include/QtStateMachine/qabstracttransition.h
/usr/include/QtStateMachine/qeventtransition.h
/usr/include/QtStateMachine/qfinalstate.h
/usr/include/QtStateMachine/qhistorystate.h
/usr/include/QtStateMachine/qkeyeventtransition.h
/usr/include/QtStateMachine/qmouseeventtransition.h
/usr/include/QtStateMachine/qsignaltransition.h
/usr/include/QtStateMachine/qstate.h
/usr/include/QtStateMachine/qstatemachine.h
/usr/include/QtStateMachine/qstatemachineglobal.h
/usr/include/QtStateMachine/qtstatemachine-config.h
/usr/include/QtStateMachine/qtstatemachineexports.h
/usr/include/QtStateMachine/qtstatemachineversion.h
/usr/lib64/cmake/Qt6BuildInternals/StandaloneTests/QtScxmlTestsConfig.cmake
/usr/lib64/cmake/Qt6Scxml/Qt6ScxmlAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6Scxml/Qt6ScxmlConfig.cmake
/usr/lib64/cmake/Qt6Scxml/Qt6ScxmlConfigVersion.cmake
/usr/lib64/cmake/Qt6Scxml/Qt6ScxmlConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6Scxml/Qt6ScxmlDependencies.cmake
/usr/lib64/cmake/Qt6Scxml/Qt6ScxmlMacros.cmake
/usr/lib64/cmake/Qt6Scxml/Qt6ScxmlTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6Scxml/Qt6ScxmlTargets.cmake
/usr/lib64/cmake/Qt6Scxml/Qt6ScxmlVersionlessTargets.cmake
/usr/lib64/cmake/Qt6ScxmlTools/Qt6ScxmlToolsAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6ScxmlTools/Qt6ScxmlToolsConfig.cmake
/usr/lib64/cmake/Qt6ScxmlTools/Qt6ScxmlToolsConfigVersion.cmake
/usr/lib64/cmake/Qt6ScxmlTools/Qt6ScxmlToolsConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6ScxmlTools/Qt6ScxmlToolsDependencies.cmake
/usr/lib64/cmake/Qt6ScxmlTools/Qt6ScxmlToolsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6ScxmlTools/Qt6ScxmlToolsTargets.cmake
/usr/lib64/cmake/Qt6ScxmlTools/Qt6ScxmlToolsVersionlessTargets.cmake
/usr/lib64/cmake/Qt6StateMachine/Qt6StateMachineAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6StateMachine/Qt6StateMachineConfig.cmake
/usr/lib64/cmake/Qt6StateMachine/Qt6StateMachineConfigVersion.cmake
/usr/lib64/cmake/Qt6StateMachine/Qt6StateMachineConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6StateMachine/Qt6StateMachineDependencies.cmake
/usr/lib64/cmake/Qt6StateMachine/Qt6StateMachineTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6StateMachine/Qt6StateMachineTargets.cmake
/usr/lib64/cmake/Qt6StateMachine/Qt6StateMachineVersionlessTargets.cmake
/usr/lib64/libQt6Scxml.prl
/usr/lib64/libQt6Scxml.so
/usr/lib64/libQt6StateMachine.prl
/usr/lib64/libQt6StateMachine.so
/usr/lib64/pkgconfig/Qt6Scxml.pc
/usr/lib64/pkgconfig/Qt6StateMachine.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt6Scxml.so.6
/usr/lib64/libQt6Scxml.so.6.6.1
/usr/lib64/libQt6StateMachine.so.6
/usr/lib64/libQt6StateMachine.so.6.6.1

%files libexec
%defattr(-,root,root,-)
/usr/libexec/qscxmlc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qt6scxml/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/qt6scxml/715f995f11805ee85601834220c43b082f457ea3
/usr/share/package-licenses/qt6scxml/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/qt6scxml/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/qt6scxml/b073f11f0c81a95ab5e32aa6b5d23a5955a95274
/usr/share/package-licenses/qt6scxml/f45ee1c765646813b442ca58de72e20a64a7ddba
